networks:
  panoseti-net:
    driver: bridge

services:
  loki:
    image: grafana/loki:3.6.0
    container_name: loki_logger
    # Run as the 'loki' user (UID 10001) for security
#    user: "10001:10001"
    ports:
      - "3100:3100"
    command:
      - "-config.file=/etc/loki/local-config.yaml"
#      - "-print-config-stderr"
    volumes:
      - ./loki-data:/loki
    networks:
      - panoseti-net
#    restart: unless-stopped
    mem_limit: 4g
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Redis (The Buffer)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - panoseti-net

  # 3. Visualization
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      # Mount your provisioning files here if you have them
      - /Users/nico/panoseti/panoseti_grafana/grafana_provisioning/:/etc/grafana/provisioning
    networks:
      - panoseti-net